server:
  port: 3001

spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: create-drop

springdoc:
  swagger-ui:
    path: /docs

rsa:
  public-key: classpath:cert/public.pem
  private-key: classpath:cert/private.pem

logging:
  level:
    org:
      springframework:
        transaction: TRACE
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
